version: '3'
services:
  db:
    image: mysql:latest
    container_name: MySQL 
    expose:
    - "1234"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}