name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install earthly
      run: sudo /bin/sh -c "$(curl -fsSL https://earthly.dev/install.sh)"

    - name: Run earthly
      run: earthly +build
